stages:
  data_ingestion:
    cmd: python src/data_ingestion/ingest.py
    deps:
      - src/data_ingestion/ingest.py
      - data/raw/telco_churn.csv
    outs:
      - data/processed/churn_ingested.csv

  data_transformation:
    cmd: python src/data_transformation/transform.py
    deps:
      - src/data_transformation/transform.py
      - data/processed/churn_ingested.csv
    outs:
      - data/processed/X_train_raw.csv
      - data/processed/X_test_raw.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/preprocessor.joblib
  training:
    cmd: python src/model_training/train.py
    deps:
      - src/model_training/train.py
      - data/processed/X_train_raw.csv
      - data/processed/y_train.csv
      - data/processed/preprocessor.joblib
    outs:
      - models/churn_model.joblib
  evaluation:
    cmd: python src/model_evaluation/evaluate.py
    deps:
      - src/model_evaluation/evaluate.py
      - models/churn_model.joblib
      - data/processed/X_test_raw.csv
      - data/processed/y_test.csv
